/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FacebookLogo: typeof import('./src/components/facebook-logo.vue')['default']
    GoogleLogo: typeof import('./src/components/google-logo.vue')['default']
    InputElement: typeof import('./src/components/InputElement.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    SocialLoginButton: typeof import('./src/components/social-login-button.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}
