// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FacebookLogo: typeof import('./src/components/facebook-logo.vue')['default']
    GoogleLogo: typeof import('./src/components/google-logo.vue')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiEmail: typeof import('~icons/mdi/email')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    InputElement: typeof import('./src/components/InputElement.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    SocialLoginButton: typeof import('./src/components/social-login-button.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}
